import { BookingRecord, DispatcherProfile, SavedDirectory } from '../types';

export const initialDispatcherProfile: DispatcherProfile = {
  companyName: 'Shakti Travels and Tours',
  tagline: 'Govt Office Fleet, Luxury Tour & VIP Taxi Services',
  gstin: '09AABCT1234F1Z8',
  pan: 'AABCT1234F',
  address: 'Nirman Bhawan Road, Hazratganj, Lucknow, Uttar Pradesh 226001',
  supportPhone: '+91 9415011223',
  bookingEmail: 'trivediabhishek78.AT@gmail.com',
  bankName: 'State Bank of India (Hazratganj Branch Lucknow)',
  bankAccountNo: '30291823901',
  ifscCode: 'SBIN0000125',
  upiId: 'shaktitravels@sbi',
  dutySlipTerms:
    '1. पार्किंग व टोल टैक्स वास्तविक रसीद अनुसार देय होगा।\n2. गाड़ी में एसी सुचारु रूप से चालू रहेगा।\n3. अतिरिक्त किलोमीटर व घंटे की दरें सरकारी टेंडर / वर्क आर्डर के अनुसार ही मान्य होंगी।',
};

export const sampleBookings: BookingRecord[] = [
  {
    id: 'BK-2026-101',
    bookingNumber: 'BK-101',
    date: new Date().toISOString().slice(0, 10),
    status: 'active_enroute',
    client: {
      name: 'Public Works Department (PWD Nirman Bhawan)',
      gstin: '09AAAGP1234E1Z1',
      billingAddress: 'Nirman Bhawan, Ashok Marg, Hazratganj, Lucknow',
      billingContactPerson: 'Executive Engineer (Accounts)',
      billingPhone: '0522-2234567',
    },
    booker: {
      name: 'Er. Pradeep Sharma (PA to Chief Engineer)',
      phone: '9415011223',
      designation: 'Staff Officer / PA',
      officeOrRoom: 'Room 304, Third Floor, Nirman Bhawan',
    },
    passenger: {
      name: 'Er. Ramesh Chandra Sharma',
      phone: '9839011223',
      designation: 'Chief Engineer (Roads & Bridges)',
      isVIP: true,
      specialRequests: 'गाड़ी में एसी लगातार चालू रहे, सफेद सीट कवर व वाटर बॉटल रखी रहे।',
    },
    vehicleNumber: 'UP32 AB 1234',
    vehicleModel: 'Maruti Suzuki Dzire VXI (White)',
    vehicleClass: 'Sedan',
    driverName: 'Rajesh Kumar Yadav',
    driverPhone: '9839011223',
    reportingDate: new Date().toISOString().slice(0, 10),
    reportingTime: '08:30 AM',
    releaseDate: new Date().toISOString().slice(0, 10),
    releaseTime: '07:30 PM',
    pickupLocation: 'कमरा नं. 304, निर्माण भवन, हजरतगंज लखनऊ',
    dropLocation: 'कानपुर-लखनऊ एक्सप्रेसवे साइट व रीजनल क्वालिटी लैब उन्नाव',
    routeStops: 'हजरतगंज ➔ ट्रांसपोर्ट नगर ➔ उन्नाव बाईपास',
    garageOutKm: 42150,
    garageInKm: undefined,
    garageOutTime: '08:00 AM',
    tariff: {
      packageType: 'local_8hr_80km',
      packageName: '8 Hours / 80 KM Local Inspection',
      baseRate: 2400,
      baseHours: 8,
      baseKm: 80,
      extraKmRate: 14,
      extraHourRate: 150,
      nightHaltRate: 350,
      driverDaRate: 300,
      extraKmRun: 65,
      extraHoursRun: 2,
      extraKmCost: 910,
      extraHourCost: 300,
      tollParkingAmount: 340,
      stateTaxPermitCost: 0,
      nightHaltAmount: 0,
      grossClientAmount: 3950,
      gstRatePercent: 5,
      gstAmount: 197.5,
      netClientBillable: 4147.5,
      driverBaseWage: 600,
      driverExtraHoursPay: 150,
      driverNightDa: 0,
      driverAdvanceDeduction: 200,
      netDriverPayable: 550,
    },
    clientInvoiceNumber: undefined,
    clientPaymentStatus: 'unbilled',
    driverPaymentStatus: 'pending',
    notes: 'माननीय मुख्य अभियंता का साइट इंस्पेक्शन दौरा।',
    createdAt: `${new Date().toISOString().slice(0, 10)} 07:30`,
    updatedAt: `${new Date().toISOString().slice(0, 10)} 08:30`,
  },
  {
    id: 'BK-2026-102',
    bookingNumber: 'BK-102',
    date: new Date().toISOString().slice(0, 10),
    status: 'dispatched',
    client: {
      name: 'National Highways Authority of India (NHAI)',
      gstin: '09AAAGN2345K1Z9',
      billingAddress: 'NHAI Regional Office, Vibhuti Khand, Gomti Nagar, Lucknow',
      billingContactPerson: 'Manager (Technical & Transport)',
      billingPhone: '0522-2720011',
    },
    booker: {
      name: 'Anil Verma (Steno to Project Director)',
      phone: '9415022334',
      designation: 'Personal Assistant',
      officeOrRoom: 'PD Secretariat, Vibhuti Khand',
    },
    passenger: {
      name: 'Shri Alok Kumar IAS',
      phone: '9839022334',
      designation: 'Project Director & CGM',
      isVIP: true,
      specialRequests: 'फास्टैग रिचार्ज पर्याप्त रहे, गाड़ी में छाता व वाटर बॉटल रखी रहे।',
    },
    vehicleNumber: 'UP32 MK 4501',
    vehicleModel: 'Toyota Innova Crysta 2.4 VX (Silver)',
    vehicleClass: 'Premium SUV',
    driverName: 'Manoj Kumar Maurya',
    driverPhone: '9839022334',
    reportingDate: new Date().toISOString().slice(0, 10),
    reportingTime: '09:00 AM',
    releaseDate: new Date().toISOString().slice(0, 10),
    pickupLocation: 'NHAI क्षेत्रीय कार्यालय, विभूति खंड गोमती नगर',
    dropLocation: 'अयोध्या बाईपास पैकेज-3 व गोरखपुर एक्सप्रेसवे निरीक्षण',
    routeStops: 'गोमती नगर ➔ बाराबंकी ➔ रामसनेहीघाट ➔ अयोध्या',
    garageOutKm: 68400,
    garageInKm: undefined,
    garageOutTime: '08:30 AM',
    tariff: {
      packageType: 'outstation',
      packageName: 'Outstation 250 KM Minimum (Innova Crysta)',
      baseRate: 4500,
      baseHours: 12,
      baseKm: 250,
      extraKmRate: 18,
      extraHourRate: 200,
      nightHaltRate: 400,
      driverDaRate: 350,
      extraKmRun: 0,
      extraHoursRun: 0,
      extraKmCost: 0,
      extraHourCost: 0,
      tollParkingAmount: 650,
      stateTaxPermitCost: 0,
      nightHaltAmount: 400,
      grossClientAmount: 5550,
      gstRatePercent: 5,
      gstAmount: 277.5,
      netClientBillable: 5827.5,
      driverBaseWage: 750,
      driverExtraHoursPay: 0,
      driverNightDa: 400,
      driverAdvanceDeduction: 500,
      netDriverPayable: 650,
    },
    clientPaymentStatus: 'unbilled',
    driverPaymentStatus: 'pending',
    notes: 'प्रोजेक्ट डायरेक्टर के साथ तकनीकी टीम मौजूद है।',
    createdAt: `${new Date().toISOString().slice(0, 10)} 08:00`,
    updatedAt: `${new Date().toISOString().slice(0, 10)} 08:45`,
  },
  {
    id: 'BK-2026-103',
    bookingNumber: 'BK-103',
    date: new Date().toISOString().slice(0, 10),
    status: 'scheduled',
    client: {
      name: 'District Collectorate Lucknow (Revenue Dept)',
      gstin: '09AAAGC3456D1Z2',
      billingAddress: 'Collectorate Camp Office, Qaiserbagh, Lucknow',
      billingContactPerson: 'Nazarat Officer / Tehsildar',
      billingPhone: '0522-2623344',
    },
    booker: {
      name: 'Suresh Singh (Reader to ADM Executive)',
      phone: '9450033445',
      designation: 'Court Reader',
      officeOrRoom: 'ADM Court Room No. 12',
    },
    passenger: {
      name: 'Smt. Sunita Verma PCS',
      phone: '9450044556',
      designation: 'ADM (Executive & Protocol)',
      isVIP: true,
      specialRequests: 'समय पर उपस्थिति अनिवार्य।',
    },
    vehicleNumber: 'UP32 LN 8844',
    vehicleModel: 'Honda Amaze VMT (White)',
    vehicleClass: 'Compact Sedan',
    driverName: 'Dharmendra Singh',
    driverPhone: '9450044556',
    reportingDate: new Date().toISOString().slice(0, 10),
    reportingTime: '10:00 AM',
    releaseDate: new Date().toISOString().slice(0, 10),
    releaseTime: '06:00 PM',
    pickupLocation: 'कलेक्ट्रेट कैम्प कार्यालय, हजरतगंज लखनऊ',
    dropLocation: 'तहसील सरोजनी नगर व विकास भवन',
    routeStops: 'हजरतगंज ➔ विधानसभा मार्ग ➔ विकास भवन',
    garageOutKm: 31200,
    tariff: {
      packageType: 'local_8hr_80km',
      packageName: '8 Hours / 80 KM Local Administrative Duty',
      baseRate: 2200,
      baseHours: 8,
      baseKm: 80,
      extraKmRate: 13,
      extraHourRate: 140,
      nightHaltRate: 350,
      driverDaRate: 300,
      extraKmRun: 0,
      extraHoursRun: 0,
      extraKmCost: 0,
      extraHourCost: 0,
      tollParkingAmount: 100,
      stateTaxPermitCost: 0,
      nightHaltAmount: 0,
      grossClientAmount: 2300,
      gstRatePercent: 5,
      gstAmount: 115,
      netClientBillable: 2415,
      driverBaseWage: 550,
      driverExtraHoursPay: 0,
      driverNightDa: 0,
      driverAdvanceDeduction: 0,
      netDriverPayable: 550,
    },
    clientPaymentStatus: 'unbilled',
    driverPaymentStatus: 'pending',
    notes: 'तहसील दिवस की प्रशासनिक बैठक।',
    createdAt: `${new Date().toISOString().slice(0, 10)} 08:15`,
  },
  {
    id: 'BK-2026-104',
    bookingNumber: 'BK-104',
    date: '2026-06-18',
    status: 'settled',
    client: {
      name: 'UP State Bridge Corporation (UPSBC)',
      gstin: '09AAABU1122D1Z5',
      billingAddress: 'Setu Bhawan, 16 Madan Mohan Malviya Marg, Lucknow',
      billingContactPerson: 'General Manager (Administration)',
      billingPhone: '0522-2208819',
    },
    booker: {
      name: 'R.K. Saxena',
      phone: '9415088219',
      designation: 'Staff Officer to MD',
      officeOrRoom: 'MD Secretariat, First Floor',
    },
    passenger: {
      name: 'Managing Director UPSBC',
      phone: '9839088219',
      designation: 'Managing Director & Secretary PWD',
      isVIP: true,
      specialRequests: 'VIP protocol fleet reception at VIP Lounge, Lucknow Airport.',
    },
    vehicleNumber: 'UP32 MK 4501',
    vehicleModel: 'Toyota Innova Crysta 2.4 VX (Silver)',
    vehicleClass: 'Premium SUV',
    driverName: 'Manoj Kumar Maurya',
    driverPhone: '9839022334',
    reportingDate: '2026-06-18',
    reportingTime: '06:00 AM',
    releaseDate: '2026-06-18',
    releaseTime: '02:00 PM',
    pickupLocation: 'चौधरी चरण सिंह अंतरराष्ट्रीय हवाई अड्डा (अमौसी अमौसी वीआईपी लाउंज)',
    dropLocation: 'सेतु भवन, लखनऊ एवं ताज होटल गोमती नगर',
    garageOutKm: 61200,
    garageInKm: 61320,
    totalKmRun: 120,
    garageOutTime: '05:30 AM',
    garageInTime: '02:30 PM',
    totalHoursRun: 9,
    tariff: {
      packageType: 'airport_station_transfer',
      packageName: 'Airport VIP Transfer & Standby (Innova Crysta)',
      baseRate: 3200,
      baseHours: 6,
      baseKm: 80,
      extraKmRate: 18,
      extraHourRate: 200,
      nightHaltRate: 400,
      driverDaRate: 350,
      extraKmRun: 40,
      extraHoursRun: 3,
      extraKmCost: 720,
      extraHourCost: 600,
      tollParkingAmount: 220,
      stateTaxPermitCost: 0,
      nightHaltAmount: 0,
      grossClientAmount: 4740,
      gstRatePercent: 5,
      gstAmount: 237,
      netClientBillable: 4977,
      driverBaseWage: 700,
      driverExtraHoursPay: 300,
      driverNightDa: 0,
      driverAdvanceDeduction: 0,
      netDriverPayable: 1000,
    },
    clientInvoiceNumber: 'INV-SFT-2026-06/044',
    clientPaymentStatus: 'paid',
    clientPaidAmount: 4977,
    driverPaymentStatus: 'settled',
    driverPaidAmount: 1000,
    notes: 'एयरपोर्ट वीआईपी आगमन व विभागीय बैठक ड्यूटी सम्पन्न। पूर्ण भुगतान प्राप्त।',
    createdAt: '2026-06-17 18:00',
    updatedAt: '2026-06-19 11:00',
  },
  {
    id: 'BK-2026-105',
    bookingNumber: 'BK-105',
    date: '2026-07-22',
    status: 'settled',
    client: {
      name: 'Public Works Department (PWD Nirman Bhawan)',
      gstin: '09AAAGP1234E1Z1',
      billingAddress: 'Nirman Bhawan, Ashok Marg, Hazratganj, Lucknow',
      billingContactPerson: 'Executive Engineer (Accounts)',
      billingPhone: '0522-2234567',
    },
    booker: {
      name: 'Er. Pradeep Sharma',
      phone: '9415011223',
      designation: 'Staff Officer / PA',
    },
    passenger: {
      name: 'Er. Ramesh Chandra Sharma',
      phone: '9839011223',
      designation: 'Chief Engineer (Roads & Bridges)',
      isVIP: true,
    },
    vehicleNumber: 'UP32 AB 1234',
    vehicleModel: 'Maruti Suzuki Dzire VXI (White)',
    vehicleClass: 'Sedan',
    driverName: 'Rajesh Kumar Yadav',
    driverPhone: '9839011223',
    reportingDate: '2026-07-22',
    reportingTime: '06:00 AM',
    releaseDate: '2026-07-23',
    releaseTime: '08:00 PM',
    pickupLocation: 'निवास स्थान, वीआईपी मॉल एवेन्यू लखनऊ',
    dropLocation: 'वाराणसी रिंग रोड फेज-2 एवं चंदौली सेतु निरीक्षण',
    routeStops: 'लखनऊ ➔ सुल्तानपुर ➔ जौनपुर ➔ वाराणसी कैंट',
    garageOutKm: 40500,
    garageInKm: 41220,
    totalKmRun: 720,
    garageOutTime: '05:30 AM',
    garageInTime: '08:30 PM',
    totalHoursRun: 38,
    tariff: {
      packageType: 'outstation',
      packageName: 'Outstation 250 KM/Day (Two Days Varanasi Tour)',
      baseRate: 5000,
      baseHours: 24,
      baseKm: 500,
      extraKmRate: 14,
      extraHourRate: 150,
      nightHaltRate: 350,
      driverDaRate: 300,
      extraKmRun: 220,
      extraHoursRun: 0,
      extraKmCost: 3080,
      extraHourCost: 0,
      tollParkingAmount: 840,
      stateTaxPermitCost: 0,
      nightHaltAmount: 350,
      grossClientAmount: 9270,
      gstRatePercent: 5,
      gstAmount: 463.5,
      netClientBillable: 9733.5,
      driverBaseWage: 1200,
      driverExtraHoursPay: 0,
      driverNightDa: 350,
      driverAdvanceDeduction: 500,
      netDriverPayable: 1050,
    },
    clientInvoiceNumber: 'INV-SFT-2026-07/089',
    clientPaymentStatus: 'paid',
    clientPaidAmount: 9733.5,
    driverPaymentStatus: 'settled',
    driverPaidAmount: 1050,
    notes: 'मुख्य अभियंता का 2 दिवसीय वाराणसी सेतु निरीक्षण दौरा। बिल भुगतान बैंक से प्राप्त।',
    createdAt: '2026-07-21 16:30',
    updatedAt: '2026-07-25 15:00',
  },
  {
    id: 'BK-2026-106',
    bookingNumber: 'BK-106',
    date: '2026-08-14',
    status: 'billed',
    client: {
      name: 'National Highways Authority of India (NHAI)',
      gstin: '09AAAGN2345K1Z9',
      billingAddress: 'NHAI Regional Office, Vibhuti Khand, Gomti Nagar, Lucknow',
      billingContactPerson: 'Manager (Technical & Transport)',
      billingPhone: '0522-2720011',
    },
    booker: {
      name: 'Anil Verma',
      phone: '9415022334',
      designation: 'Personal Assistant',
    },
    passenger: {
      name: 'Shri Alok Kumar IAS',
      phone: '9839022334',
      designation: 'Project Director & CGM',
      isVIP: true,
    },
    vehicleNumber: 'UP32 MK 4501',
    vehicleModel: 'Toyota Innova Crysta 2.4 VX (Silver)',
    vehicleClass: 'Premium SUV',
    driverName: 'Manoj Kumar Maurya',
    driverPhone: '9839022334',
    reportingDate: '2026-08-14',
    reportingTime: '08:00 AM',
    releaseDate: '2026-08-14',
    releaseTime: '09:00 PM',
    pickupLocation: 'NHAI क्षेत्रीय कार्यालय गोमती नगर',
    dropLocation: 'गोरखपुर लिंक एक्सप्रेसवे व बस्ती बाईपास',
    garageOutKm: 65200,
    garageInKm: 65680,
    totalKmRun: 480,
    garageOutTime: '07:30 AM',
    garageInTime: '09:30 PM',
    totalHoursRun: 14,
    tariff: {
      packageType: 'outstation',
      packageName: 'Outstation 250 KM Min (Innova Crysta)',
      baseRate: 4500,
      baseHours: 12,
      baseKm: 250,
      extraKmRate: 18,
      extraHourRate: 200,
      nightHaltRate: 400,
      driverDaRate: 350,
      extraKmRun: 230,
      extraHoursRun: 2,
      extraKmCost: 4140,
      extraHourCost: 400,
      tollParkingAmount: 720,
      stateTaxPermitCost: 0,
      nightHaltAmount: 0,
      grossClientAmount: 9760,
      gstRatePercent: 5,
      gstAmount: 488,
      netClientBillable: 10248,
      driverBaseWage: 750,
      driverExtraHoursPay: 300,
      driverNightDa: 0,
      driverAdvanceDeduction: 400,
      netDriverPayable: 650,
    },
    clientInvoiceNumber: 'INV-SFT-2026-08/112',
    clientPaymentStatus: 'paid',
    clientPaidAmount: 10248,
    driverPaymentStatus: 'settled',
    driverPaidAmount: 650,
    notes: 'प्रोजेक्ट डायरेक्टर एक्सप्रेसवे पैकेज-2 समीक्षा पूर्ण।',
    createdAt: '2026-08-13 14:00',
    updatedAt: '2026-08-16 12:00',
  },
  {
    id: 'BK-2026-107',
    bookingNumber: 'BK-107',
    date: '2026-09-18',
    status: 'billed',
    client: {
      name: 'District Collectorate Lucknow (Revenue Dept)',
      gstin: '09AAAGC3456D1Z2',
      billingAddress: 'Collectorate Camp Office, Qaiserbagh, Lucknow',
      billingContactPerson: 'Nazarat Officer / Tehsildar',
      billingPhone: '0522-2623344',
    },
    booker: {
      name: 'Suresh Singh',
      phone: '9450033445',
      designation: 'Court Reader',
    },
    passenger: {
      name: 'Smt. Sunita Verma PCS',
      phone: '9450044556',
      designation: 'ADM (Executive & Protocol)',
      isVIP: true,
    },
    vehicleNumber: 'UP32 LN 8844',
    vehicleModel: 'Honda Amaze VMT (White)',
    vehicleClass: 'Compact Sedan',
    driverName: 'Dharmendra Singh',
    driverPhone: '9450044556',
    reportingDate: '2026-09-18',
    reportingTime: '09:00 AM',
    releaseDate: '2026-09-18',
    releaseTime: '07:00 PM',
    pickupLocation: 'कलेक्ट्रेट कैम्प कार्यालय, हजरतगंज',
    dropLocation: 'मोहनलालगंज व बख्शी का तालाब तहसील दिवस दौरा',
    garageOutKm: 31900,
    garageInKm: 32040,
    totalKmRun: 140,
    garageOutTime: '08:30 AM',
    garageInTime: '07:30 PM',
    totalHoursRun: 11,
    tariff: {
      packageType: 'local_8hr_80km',
      packageName: '8 Hours / 80 KM Local Administrative Duty',
      baseRate: 2200,
      baseHours: 8,
      baseKm: 80,
      extraKmRate: 13,
      extraHourRate: 140,
      nightHaltRate: 350,
      driverDaRate: 300,
      extraKmRun: 60,
      extraHoursRun: 3,
      extraKmCost: 780,
      extraHourCost: 420,
      tollParkingAmount: 150,
      stateTaxPermitCost: 0,
      nightHaltAmount: 0,
      grossClientAmount: 3550,
      gstRatePercent: 5,
      gstAmount: 177.5,
      netClientBillable: 3727.5,
      driverBaseWage: 550,
      driverExtraHoursPay: 200,
      driverNightDa: 0,
      driverAdvanceDeduction: 0,
      netDriverPayable: 750,
    },
    clientInvoiceNumber: 'INV-SFT-2026-09/154',
    clientPaymentStatus: 'invoiced',
    driverPaymentStatus: 'settled',
    driverPaidAmount: 750,
    notes: 'तहसील संपूर्ण समाधान दिवस प्रोटोकॉल ड्यूटी सम्पन्न। इनवॉइस कार्यालय को प्रेषित।',
    createdAt: '2026-09-17 17:00',
    updatedAt: '2026-09-19 10:00',
  },
];

export const loadSavedDirectory = (currentBookings: BookingRecord[] = []): SavedDirectory => {
  try {
    const raw = localStorage.getItem('fleetdispatch_saved_directory');
    if (raw) {
      const parsed = JSON.parse(raw);
      if (parsed.clients && parsed.bookers) return parsed;
    }
  } catch {}

  // Build directory from bookings
  const clientsMap = new Map();
  const bookersMap = new Map();
  const passengersMap = new Map();
  const vehiclesMap = new Map();
  const driversMap = new Map();

  currentBookings.forEach((b) => {
    if (b.client?.name) clientsMap.set(b.client.name, b.client);
    if (b.booker?.name) bookersMap.set(b.booker.name, b.booker);
    if (b.passenger?.name) passengersMap.set(b.passenger.name, b.passenger);
    if (b.vehicleNumber) {
      vehiclesMap.set(b.vehicleNumber, {
        vehicleNumber: b.vehicleNumber,
        vehicleModel: b.vehicleModel,
        vehicleClass: b.vehicleClass,
      });
    }
    if (b.driverName) {
      driversMap.set(b.driverName, {
        name: b.driverName,
        phone: b.driverPhone,
      });
    }
  });

  return {
    clients: Array.from(clientsMap.values()),
    bookers: Array.from(bookersMap.values()),
    passengers: Array.from(passengersMap.values()),
    vehicles: Array.from(vehiclesMap.values()),
    drivers: Array.from(driversMap.values()),
  };
};

export const saveDirectoryToStorage = (dir: SavedDirectory) => {
  try {
    localStorage.setItem('fleetdispatch_saved_directory', JSON.stringify(dir));
  } catch {}
};
